# Generated by Django 4.2.dev20221230122847 on 2023-02-07 19:20

import connection.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_remove_userconnection_connection_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodename', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('connection', models.ForeignKey(default=connection.models.Connection.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='connection.connection')),
            ],
        ),
    ]
